apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: kubernetes.azure.com/scalesetpriority
          operator: Exists
      nodeSelector:
        agentpool: {{ .Values.nodePool }}
      containers:
        - name: next
          image: codegarten-fff5gyfuhxddhfhu.azurecr.io/omegadent-web-next:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: APP_VERSION
              value: {{ .Chart.AppVersion }}
            - name: NEXTAUTH_URL
              value: https://{{ .Values.hostName }}/login
            - name: STRAPI_BASE_URL
              value: 127.0.0.1:1337
            - name: NEXT_PUBLIC_ORIGIN
              value: https://{{ .Values.hostName }}
            - name: NEXT_PUBLIC_STRAPI_JWT_EXPIRES_SEC
              value: "600"
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-nextauth-secret
                  key: NEXTAUTH_SECRET
            - name: NEXT_STRAPI_FULL_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-next-strapi-full-access-token
                  key: NEXT_STRAPI_FULL_ACCESS_TOKEN
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-next-telegram-bot-token
                  key: TELEGRAM_BOT_TOKEN
            - name: TELEGRAM_ADMIN_CHAT_IDS
              value: {{ .Values.telegramAdminChatIds }}
          volumeMounts:
            - name: {{ .Values.appName }}-secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
            - name: {{ .Values.appName }}-strapi-uploads
              mountPath: /app/public/uploads
        - name: strapi
          image: codegarten-fff5gyfuhxddhfhu.azurecr.io/omegadent-web-strapi:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
          env:
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: "1337"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: STRAPI_BASE_URL
              value: 127.0.0.1:1337
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-app-keys
                  key: APP_KEYS
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-api-token-salt
                  key: API_TOKEN_SALT
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-admin-jwt-secret
                  key: ADMIN_JWT_SECRET
            - name: TRANSFER_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-transfer-token-salt
                  key: TRANSFER_TOKEN_SALT
            - name: DATABASE_CLIENT
              value: postgres
            - name: DATABASE_HOST
              value: {{ .Values.databaseHost }}
            - name: DATABASE_PORT
              value: "{{ .Values.databasePort }}"
            - name: DATABASE_NAME
              value: {{ .Values.databaseName }}
            - name: DATABASE_USERNAME
              value: {{ .Values.databaseUsername }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-database-password
                  key: DATABASE_PASSWORD
            - name: DATABASE_SSL
              value: "true"
            - name: MAIL_HOST
              value: {{ .Values.mailHost }}
            - name: MAIL_PORT
              value: {{ .Values.mailPort }}
            - name: MAIL_USERNAME
              value: {{ .Values.mailUsername }}
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-mail-password
                  key: MAIL_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-jwt-secret
                  key: JWT_SECRET
            - name: JWT_SECRET_EXPIRES
              value: "600" # 10 min in seconds
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.appName }}-refresh-token-secret
                  key: REFRESH_TOKEN_SECRET
            - name: REFRESH_TOKEN_EXPIRES
              value: "21600" # 6 hours in seconds
            - name: TZ
              value: UTC
            - name: STRAPI_TELEMETRY_DISABLED
              value: "true"
          volumeMounts:
            - name: {{ .Values.appName }}-secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
            - name: {{ .Values.appName }}-strapi-uploads
              mountPath: /opt/app/public/uploads
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: {{ .Values.appName }}-nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: {{ .Values.appName }}-nginx-config
          configMap:
            name: {{ .Values.appName }}-nginx-config
        - name: {{ .Values.appName }}-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.appName }}-key-vault
        - name: {{ .Values.appName }}-strapi-uploads
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}-azure-file
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-nginx-config
  labels:
    app: {{ .Values.appName }}
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        server_name {{ .Values.hostName }};
        location / {
          proxy_set_header Host $http_host;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header X-Real-IP $remote_addr;
          proxy_pass http://127.0.0.1:3000;
        }
        location /cms/ {
          rewrite ^/cms/?(.*)$ /$1 break;
          proxy_pass http://127.0.0.1:1337;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Host $http_host;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_pass_request_headers on;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-protocol: "tcp"
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-ingress
  annotations:
    cert-manager.io/issuer: {{ .Values.appName }}-letsencrypt-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.hostName }}
      secretName: letsencrypt-tls
  rules:
    - host: {{ .Values.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}-service
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-letsencrypt-issuer
spec:
  acme:
    email: {{ .Values.letsencryptEmail }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Values.appName }}-letsencrypt-account-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-letsencrypt-cert
spec:
  secretName: letsencrypt-tls
  issuerRef:
    name: {{ .Values.appName }}-letsencrypt-issuer
  commonName: {{ .Values.hostName }}
  dnsNames:
    - {{ .Values.hostName }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-key-vault
spec:
  provider: azure
  parameters:
    usePodIdentity: "false" # Should be quoted
    useVMManagedIdentity: "true" # Should be quoted
    tenantId: {{ .Values.tenantId }}
    keyvaultName: {{ .Values.keyVault }}
    userAssignedIdentityID: {{ .Values.managedIdentityId }}
    objects: |
      array:
        - |
          objectName: {{ .Values.appName }}-next-auth-secret
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-next-strapi-full-access-token
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-next-telegram-bot-token
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-transfer-token-salt
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-jwt-secret
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-admin-jwt-secret
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-api-token-salt
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-app-keys
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-refresh-token-secret
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-database-password
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-mail-password
          objectType: secret
  secretObjects:
    - secretName: {{ .Values.appName }}-nextauth-secret
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-next-auth-secret
          key: NEXTAUTH_SECRET
    - secretName: {{ .Values.appName }}-next-strapi-full-access-token
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-next-strapi-full-access-token
          key: NEXT_STRAPI_FULL_ACCESS_TOKEN
    - secretName: {{ .Values.appName }}-next-telegram-bot-token
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-next-telegram-bot-token
          key: TELEGRAM_BOT_TOKEN
    - secretName: {{ .Values.appName }}-jwt-secret
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-jwt-secret
          key: JWT_SECRET
    - secretName: {{ .Values.appName }}-transfer-token-salt
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-transfer-token-salt
          key: TRANSFER_TOKEN_SALT
    - secretName: {{ .Values.appName }}-admin-jwt-secret
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-admin-jwt-secret
          key: ADMIN_JWT_SECRET
    - secretName: {{ .Values.appName }}-api-token-salt
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-api-token-salt
          key: API_TOKEN_SALT
    - secretName: {{ .Values.appName }}-app-keys
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-app-keys
          key: APP_KEYS
    - secretName: {{ .Values.appName }}-refresh-token-secret
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-refresh-token-secret
          key: REFRESH_TOKEN_SECRET
    - secretName: {{ .Values.appName }}-database-password
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-database-password
          key: DATABASE_PASSWORD
    - secretName: {{ .Values.appName }}-mail-password
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-mail-password
          key: MAIL_PASSWORD
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-azure-file
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: {{ .Values.storage }}
