apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: kubernetes.azure.com/scalesetpriority
          operator: Exists
      nodeSelector:
        agentpool: {{ .Values.nodePool }}
      initContainers:
        - name: put-static-frontend
          image: codegarten-fff5gyfuhxddhfhu.azurecr.io/managex-frontend:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          env:
            - name: TARGET_DIR
              value: /frontend
          volumeMounts:
            - name: frontend
              mountPath: /frontend
        - name: put-static-frontend-tablet
          image: codegarten-fff5gyfuhxddhfhu.azurecr.io/managex-frontend-tablet:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          env:
            - name: TARGET_DIR
              value: /frontend-tablet
          volumeMounts:
            - name: frontend-tablet
              mountPath: /frontend-tablet
      containers:
        - name: strapi
          image: codegarten-fff5gyfuhxddhfhu.azurecr.io/managex-strapi:{{ .Chart.AppVersion }}
          imagePullPolicy: Always
          ports:
            - containerPort: 1337
          env:
            - name: HOST
              value: 0.0.0.0
            - name: PORT
              value: "1337"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: STRAPI_BASE_URL
              value: 127.0.0.1:1337
            - name: APP_KEYS
              valueFrom:
                secretKeyRef:
                  name: app-keys
                  key: APP_KEYS
            - name: API_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: api-token-salt
                  key: API_TOKEN_SALT
            - name: ADMIN_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: admin-jwt-secret
                  key: ADMIN_JWT_SECRET
            - name: TRANSFER_TOKEN_SALT
              valueFrom:
                secretKeyRef:
                  name: transfer-token-salt
                  key: TRANSFER_TOKEN_SALT
            - name: DATABASE_CLIENT
              value: postgres
            - name: DATABASE_HOST
              value: {{ .Values.databaseHost }}
            - name: DATABASE_PORT
              value: "{{ .Values.databasePort }}"
            - name: DATABASE_NAME
              value: {{ .Values.databaseName }}
            - name: DATABASE_USERNAME
              value: {{ .Values.databaseUsername }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password
                  key: DATABASE_PASSWORD
            - name: DATABASE_SSL
              value: "true"
            - name: SMTP_HOST
              value: {{ .Values.smtpHost }}
            - name: SMTP_PORT
              value: "{{ .Values.smtpPort }}"
            - name: SMTP_USERNAME
              value: {{ .Values.smtpUsername }}
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mail-password
                  key: SMTP_PASSWORD
            - name: MAIL_FROM
              value: {{ .Values.mailFrom }}
            - name: MAIL_REPLY_TO
              value: {{ .Values.mailReplyTo }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: JWT_SECRET_EXPIRES
              value: "600" # 10 min in seconds
            - name: REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: refresh-token-secret
                  key: REFRESH_TOKEN_SECRET
            - name: REFRESH_TOKEN_EXPIRES
              value: "21600" # 6 hours in seconds
            - name: TZ
              value: UTC
            - name: STRAPI_TELEMETRY_DISABLED
              value: "true"
          volumeMounts:
            - name: {{ .Values.appName }}-secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true
            - name: {{ .Values.appName }}-strapi-uploads
              mountPath: /opt/app/public/uploads
        - name: nginx
          image: nginx:1.29-alpine
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: frontend
              mountPath: /var/www/frontend/static
            - name: frontend-tablet
              mountPath: /var/www/frontend-tablet/static
            - name: tls-certs
              mountPath: /etc/nginx/tls
              readOnly: true
            - name: {{ .Values.appName }}-nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: frontend
          emptyDir: {}
        - name: frontend-tablet
          emptyDir: {}
        - name: tls-certs
          secret:
            secretName: self-signed-tls
        - name: {{ .Values.appName }}-nginx-config
          configMap:
            name: {{ .Values.appName }}-nginx-config
        - name: {{ .Values.appName }}-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.appName }}-key-vault
        - name: {{ .Values.appName }}-strapi-uploads
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}-azure-file
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-nginx-config
  labels:
    app: {{ .Values.appName }}
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        server_name {{ .Values.hostName }};
        types {
          application/javascript js;
          text/html html htm;
          text/css css;
          image/svg+xml svg;
          image/png png;
        }
        location / {
          root /var/www/frontend/static;
          index index.html;
          try_files $uri /index.html;
        }
        location /cms/ {
          rewrite ^/cms/?(.*)$ /$1 break;
          proxy_pass http://127.0.0.1:1337;
          proxy_http_version 1.1;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Host $http_host;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_pass_request_headers on;
        }
      }
      server {
        listen 80;
        server_name {{ .Values.tabletHostName }};
        types {
          application/javascript js;
          text/html html htm;
          text/css css;
          image/svg+xml svg;
          image/png png;
        }
        location / {
          root /var/www/frontend-tablet/static;
          index index.html;
          try_files $uri /index.html;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-ingress
  annotations:
    cert-manager.io/issuer: {{ .Values.appName }}-self-signed-issuer
spec:
  ingressClassName: private-nginx
  tls:
    - hosts:
        - {{ .Values.hostName }}
        - {{ .Values.tabletHostName }}
      secretName: self-signed-tls
  rules:
    - host: {{ .Values.hostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}-service
                port:
                  number: 80
    - host: {{ .Values.tabletHostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName }}-service
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-self-signed-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-self-signed-cert
spec:
  secretName: self-signed-tls
  issuerRef:
    name: {{ .Values.appName }}-self-signed-issuer
  dnsNames:
    - {{ .Values.hostName }}
    - {{ .Values.tabletHostName }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-key-vault
spec:
  provider: azure
  parameters:
    usePodIdentity: "false" # Should be quoted
    useVMManagedIdentity: "true" # Should be quoted
    tenantId: {{ .Values.tenantId }}
    keyvaultName: {{ .Values.keyVault }}
    userAssignedIdentityID: {{ .Values.managedIdentityId }}
    objects: |
      array:
        - |
          objectName: {{ .Values.appName }}-strapi-transfer-token-salt
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-jwt-secret
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-admin-jwt-secret
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-api-token-salt
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-app-keys
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-refresh-token-secret
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-database-password
          objectType: secret
        - |
          objectName: {{ .Values.appName }}-strapi-mail-password
          objectType: secret
  secretObjects:
    - secretName: jwt-secret
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-jwt-secret
          key: JWT_SECRET
    - secretName: transfer-token-salt
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-transfer-token-salt
          key: TRANSFER_TOKEN_SALT
    - secretName: admin-jwt-secret
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-admin-jwt-secret
          key: ADMIN_JWT_SECRET
    - secretName: api-token-salt
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-api-token-salt
          key: API_TOKEN_SALT
    - secretName: app-keys
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-app-keys
          key: APP_KEYS
    - secretName: refresh-token-secret
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-refresh-token-secret
          key: REFRESH_TOKEN_SECRET
    - secretName: database-password
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-database-password
          key: DATABASE_PASSWORD
    - secretName: mail-password
      type: Opaque
      data:
        - objectName: {{ .Values.appName }}-strapi-mail-password
          key: SMTP_PASSWORD
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}-azure-file
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  resources:
    requests:
      storage: {{ .Values.storage }}
